name: flutter_infinite_dropdown
description: This Flutter package helps create a dropdown which is fully customized And also provides a feature pagination.
version: 1.0.2+3

homepage: https://github.com/Zaveri21/flutter_infinite_dropdown
repository: https://github.com/Zaveri21/flutter_infinite_dropdown
issue_tracker: https://github.com/Zaveri21/flutter_infinite_dropdown/issues

environment:
  sdk: ">=2.18.6 <4.0.0"
  #sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

platforms:
  android:
  ios:

funding:
  - url: https://buymeacoffee.com/vishaljhaveri